# This file defines the config for "ct" (chart tester) used by the helm linting GitHub workflow

lint-conf: .ci/lint-config.yaml
target-branch: master
validate-maintainers: false
check-version-increment: false
