{{- if and (.Values.deployment.env.ENABLE_RSPAMD) (.Values.rspamd.ingress.enabled) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "dockermailserver.fullname" . }}-rspamd
{{- with .Values.rspamd.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.rspamd.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.rspamd.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: {{ .Values.rspamd.ingress.path }}
            backend:
              service:
                name: {{ template "dockermailserver.fullname" . }}
                port:
                  name: rspamd

{{ if .Values.rspamd.ingress.tls.enabled }}
  tls:
  - secretName: {{ .Values.rspamd.ingress.tls.secret }}
    hosts:
    -  {{ .Values.rspamd.ingress.host }}
{{- end }}
{{- end }}