{{- if .Values.rainloop.enabled -}}
{{- if .Values.rainloop.ingress.enabled -}}
{{- $fullName := include "dockermailserver.fullname" . -}}
{{- $servicePort := .Values.rainloop.service.port -}}
{{- $ingressPath := .Values.rainloop.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "dockermailserver.fullname" . }}
{{- with .Values.rainloop.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.rainloop.ingress.tls }}
  tls:
  {{- range .Values.rainloop.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.rainloop.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - pathType: Prefix
            path: {{ $ingressPath }}
            backend:
              service:
                name: {{ $fullName }}-rainloop
                port:
                  number: {{ $servicePort }}
  {{- end }}
{{- end }}
{{- end }}
