{{- range $name, $pvc := .Values.persistent_volume_claims -}}
{{- if and (not $pvc.existingClaim) ($pvc.enabled) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "dockermailserver.fullname" $ }}-{{ $name }}
  {{- if $pvc.annotations }}
  annotations:
    {{ toYaml $pvc.annotations }}  
  {{ end }}
spec:
  accessModes:
  {{ toYaml $pvc.accessModes | indent 2 }}
    
  {{- if $pvc.storageClass }}
  storageClassName: {{ $pvc.storageClass | quote }}
  {{- end }}    
  resources:
    requests:
      storage: {{ $pvc.size | quote }}
  {{- if $pvc.selector }}
  selector:
{{ toYaml $pvc.selector | indent 4 }}
  {{ end }}
---
{{- end }}
{{- end }}
