{
 "title": "postfix-details",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "{ \"find\" : \"terms\" , \"field\": \"cluster.keyword\", \"size\":0 }"
   },
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,week,month,quarter,year"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Messages total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "_exists_:to AND service:\"postfix/smtp\" AND cluster:$cluster",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "sent - count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "_exists_:to AND service:\"postfix/smtp\" AND cluster:$cluster AND status:sent",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "deferred- count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "_exists_:to AND service:\"postfix/smtp\" AND cluster:$cluster AND status:deferred",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "bounced- Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:to AND service:\"postfix/smtp\" AND cluster:$cluster AND status:bounced",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "expired - Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:to AND service:\"postfix/smtp\" AND cluster:$cluster AND status:expired",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "unknown - Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:to AND service:\"postfix/smtp\" AND cluster:$cluster AND !_exists_:status",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "postfix/smtp",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status.keyword",
       "id": "5",
       "settings": {
        "min_doc_count": "0",
        "missing": "unknown",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "time",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:to AND service:\"postfix/smtp\" AND cluster:$cluster",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "hostname",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "hostname.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:to AND service:\"postfix/smtp\" AND cluster:$cluster",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Top senders",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "to.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "_exists_:to AND service:\"postfix/smtp\" AND cluster:$cluster",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "postfix/smtp",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "logs"
      }
     ],
     "query": "_exists_:to AND service:\"postfix/smtp\" AND cluster:$cluster",
     "timeField": "time"
    }
   ]
  }
 ]
}